# Generated by Django 6.0.4 on 2026-04-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagechecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_checked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
