# Generated by Django 6.0.4 on 2026-04-12 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagechecker', '0002_alter_page_last_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='pagechecker.page'),
        ),
    ]
