# Generated by Django 6.0.4 on 2026-04-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagechecker', '0003_alter_snapshot_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='html_content',
            field=models.TextField(default=''),
        ),
    ]
