# Generated by Django 6.0.4 on 2026-04-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagechecker', '0004_snapshot_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
