# Generated by Django 6.0.4 on 2026-04-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagechecker', '0007_snapshot_body_html_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
