# Generated by Django 6.0.4 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagechecker", "0008_snapshot_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="content_insights",
            field=models.JSONField(default=dict),
        ),
    ]
