# Generated by Django 6.0.4 on 2026-04-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagechecker', '0010_remove_snapshot_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
