# Generated by Django 6.0.4 on 2026-04-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagechecker', '0015_page_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='should_report_daily',
            field=models.BooleanField(default=False),
        ),
    ]
