# Generated by Django 6.0.4 on 2026-04-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagechecker', '0022_page_question_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='feature_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='feature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
