# Generated by Django 6.0.4 on 2026-05-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0004_rename_series_seriesitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="cover_image_base64",
            field=models.TextField(
                blank=True,
                help_text="First page of first CBZ in series (natural sort), standard base64.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="cover_image_mime_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MIME type for decoded cover bytes (e.g. image/jpeg).",
                max_length=64,
            ),
        ),
    ]
