# Generated by Django 6.0.4 on 2026-05-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0006_cbzconvertjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="seriesitem",
            name="cover_image_base64",
            field=models.TextField(
                blank=True,
                help_text="First image page in this CBZ (natural sort), standard base64 JPEG thumb.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="seriesitem",
            name="cover_image_mime_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MIME type for decoded cover bytes (e.g. image/jpeg).",
                max_length=64,
            ),
        ),
    ]
