# Generated by Django 5.1

from django.db import migrations, models
from django.utils import timezone


def backfill_dropbox_uploaded_at(apps, schema_editor):
    SeriesItem = apps.get_model("manga", "SeriesItem")
    now = timezone.now()
    SeriesItem.objects.all().update(dropbox_uploaded_at=now)


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0012_merge_series_category_seriesitem_file_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="seriesitem",
            name="dropbox_uploaded_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="When this CBZ was uploaded to Dropbox (app-side; null if never uploaded).",
            ),
        ),
        migrations.RunPython(backfill_dropbox_uploaded_at, migrations.RunPython.noop),
    ]
