# Generated by Django 6.0.4 on 2026-05-04 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0020_rename_seriesinfo_mangabaka_type_series_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleDriveBackupJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "manga_root",
                    models.CharField(
                        help_text="Normalized absolute manga library root when job was created.",
                        max_length=4096,
                    ),
                ),
                (
                    "series_item_id",
                    models.PositiveIntegerField(help_text="Primary key of SeriesItem to upload."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_message", models.TextField(blank=True, null=True)),
                (
                    "google_drive_file_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Drive file id after successful upload.",
                        max_length=128,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="google_drive_backup_jobs",
                        to="manga.series",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manga_google_drive_backup_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["user_id", "manga_root", "series_id"], name="manga_gdrive_user_root_series"),
                ],
            },
        ),
    ]
