# Generated by Django 6.0.4 on 2026-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0021_google_drive_backup_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googledrivebackupjob",
            name="series_item_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Primary key of SeriesItem to upload (null only for legacy rows).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="googledrivebackupjob",
            name="google_drive_file_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Drive file id after successful upload or when an existing file was reused.",
                max_length=128,
            ),
        ),
    ]
