# Generated by Django 6.0.4 on 2026-02-09 00:00

from django.db import migrations, models


def _delete_all_google_drive_backup_jobs(apps, schema_editor):
    GoogleDriveBackupJob = apps.get_model("manga", "GoogleDriveBackupJob")
    GoogleDriveBackupJob.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("manga", "0022_googledrivebackupjob_series_item_nullable"),
    ]

    operations = [
        migrations.RunPython(_delete_all_google_drive_backup_jobs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="googledrivebackupjob",
            name="series_item_id",
            field=models.PositiveIntegerField(
                help_text="Primary key of SeriesItem to upload.",
            ),
        ),
    ]
