# Generated by Django 5.0

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0027_rename_seriesitem_is_google_drive_backed_up_is_backed_up"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleDriveRestoreJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "manga_root",
                    models.CharField(
                        help_text="Normalized absolute manga library root when job was created.",
                        max_length=4096,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_message", models.TextField(blank=True, null=True)),
                (
                    "restored_file_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Non-folder files written from Drive (after job completes successfully).",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="google_drive_restore_jobs",
                        to="manga.series",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manga_google_drive_restore_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "Google Drive restore job",
                "verbose_name_plural": "Google Drive restore jobs",
            },
        ),
        migrations.AddIndex(
            model_name="googledriverestorejob",
            index=models.Index(fields=["user_id", "manga_root", "series_id"], name="manga_gdrive_rst_user_root_ser"),
        ),
    ]
