# Generated by Django 6.0

from django.db import migrations, models
from django.utils import timezone


def _backfill_single_pending_lock(apps, schema_editor):
    GoogleDriveRestoreJob = apps.get_model("manga", "GoogleDriveRestoreJob")
    lock = 1
    status_pending = "pending"
    status_failed = "failed"
    msg = "Cancelled: only one restore may be pending at a time (migration)."
    q = GoogleDriveRestoreJob.objects.filter(status=status_pending)
    if not q.exists():
        return
    ordered = list(q.order_by("created_at", "pk"))
    keep = ordered[0]
    keep.pending_lock = lock
    keep.save(update_fields=["pending_lock"])
    now = timezone.now()
    for row in ordered[1:]:
        row.status = status_failed
        row.completed_at = now
        row.failure_message = msg
        row.pending_lock = 0
        row.save(update_fields=["status", "completed_at", "failure_message", "pending_lock"])


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0028_googledriverestorejob"),
    ]

    operations = [
        migrations.AddField(
            model_name="googledriverestorejob",
            name="pending_lock",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text=(
                    "1 while this row is the queued restore; 0 after completed/failed. "
                    "At most one pending job may use this value."
                ),
            ),
        ),
        migrations.RunPython(_backfill_single_pending_lock, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="googledriverestorejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="pending", pending_lock=1),
                fields=("pending_lock",),
                name="manga_gdrive_restore_one_pending",
            ),
        ),
    ]
