# Generated by Django 6.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0029_googledriverestorejob_single_pending_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googledriverestorejob",
            name="series",
            field=models.ForeignKey(
                blank=True,
                help_text="Null when restoring every series folder under the Drive Manga root.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="google_drive_restore_jobs",
                to="manga.series",
            ),
        ),
    ]
