# Generated by Django 6.0

from django.db import migrations, models


def _backfill_series_name_from_fk(apps, schema_editor):
    Job = apps.get_model("manga", "GoogleDriveRestoreJob")
    Series = apps.get_model("manga", "Series")
    for job in Job.objects.all():
        if job.series_id is None:
            Job.objects.filter(pk=job.pk).update(series_name=None)
        else:
            try:
                s = Series.objects.get(pk=job.series_id)
                Job.objects.filter(pk=job.pk).update(series_name=s.name)
            except Series.DoesNotExist:
                Job.objects.filter(pk=job.pk).update(series_name=None)
    Job.objects.filter(series_name="").update(series_name=None)


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0030_googledriverestorejob_series_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="googledriverestorejob",
            name="series_name",
            field=models.CharField(
                blank=True,
                help_text="Set from migration; Drive series folder basename.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.RunPython(_backfill_series_name_from_fk, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="googledriverestorejob",
            name="manga_gdrive_rst_user_root_ser",
        ),
        migrations.RemoveField(
            model_name="googledriverestorejob",
            name="series",
        ),
        migrations.AlterField(
            model_name="googledriverestorejob",
            name="series_name",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Drive series folder basename; null or blank restores every series subfolder under Manga."
                ),
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="googledriverestorejob",
            index=models.Index(
                fields=["user_id", "manga_root", "series_name"],
                name="manga_gdrive_rst_user_root_nm",
            ),
        ),
    ]
