# Generated by Django 6.0.4 on 2026-05-01 15:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('PERSONAL', 'Personal'), ('FAMILY', 'Family')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Relative weight for pro-rata allocation among selected assets.', max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='CLP', help_text='ISO 4217 currency code (e.g. CLP).', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scope', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('PERSONAL', 'Personal'), ('FAMILY', 'Family')], db_index=True, max_length=16)),
                ('budget_amount', models.DecimalField(decimal_places=2, help_text='Total amount distributed in this run (signed).', max_digits=14)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DistributionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lines', to='savings.asset')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='savings.distribution')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_families_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.AddField(
            model_name='distribution',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='savings.family'),
        ),
        migrations.AddField(
            model_name='asset',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_assets', to='savings.family'),
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='savings.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='distribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', True), ('scope', 'PERSONAL')), models.Q(('family__isnull', False), ('scope', 'FAMILY')), _connector='OR'), name='savings_distribution_scope_family_consistent'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'PERSONAL')), fields=('owner', 'name'), name='savings_asset_personal_owner_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'FAMILY')), fields=('family', 'name'), name='savings_asset_family_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', True), ('scope', 'PERSONAL')), models.Q(('family__isnull', False), ('scope', 'FAMILY')), _connector='OR'), name='savings_asset_scope_family_consistent'),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(fields=('family', 'user'), name='savings_family_membership_uniq'),
        ),
    ]
