# Generated by Django 6.0.4 on 2026-05-01 13:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('PERSONAL', 'Personal'), ('FAMILY', 'Family')], db_index=True, max_length=16)),
                ('budget_amount', models.DecimalField(decimal_places=2, help_text='Total amount distributed in this session (signed).', max_digits=14)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_distribution_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SavingsAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('PERSONAL', 'Personal'), ('FAMILY', 'Family')], db_index=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='Relative weight for pro-rata allocation among selected assets.', max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='CLP', help_text='ISO 4217 currency code (e.g. CLP).', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scope', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DistributionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name_snapshot', models.CharField(max_length=255)),
                ('weight_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('selected', models.BooleanField(default=True)),
                ('share_percent', models.DecimalField(decimal_places=4, help_text='Percent of selected weight total (0–100).', max_digits=7)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='savings.distributionsession')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_lines', to='savings.savingsasset')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='savingsasset',
            constraint=models.UniqueConstraint(fields=('owner', 'scope', 'name'), name='savings_asset_owner_scope_name_uniq'),
        ),
    ]
