# Generated by Django 6.0.4 on 2026-05-01 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'families',
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='savingsasset',
            name='savings_asset_owner_scope_name_uniq',
        ),
        migrations.AddField(
            model_name='family',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_families_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distributionsession',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_sessions', to='savings.family'),
        ),
        migrations.AddField(
            model_name='savingsasset',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings_assets', to='savings.family'),
        ),
        migrations.AddConstraint(
            model_name='distributionsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', True), ('scope', 'PERSONAL')), models.Q(('family__isnull', False), ('scope', 'FAMILY')), _connector='OR'), name='savings_session_scope_family_consistent'),
        ),
        migrations.AddConstraint(
            model_name='savingsasset',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'PERSONAL')), fields=('owner', 'name'), name='savings_asset_personal_owner_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='savingsasset',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'FAMILY')), fields=('family', 'name'), name='savings_asset_family_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='savingsasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', True), ('scope', 'PERSONAL')), models.Q(('family__isnull', False), ('scope', 'FAMILY')), _connector='OR'), name='savings_asset_scope_family_consistent'),
        ),
        migrations.AddField(
            model_name='familymembership',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='savings.family'),
        ),
        migrations.AddField(
            model_name='familymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_family_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='familymembership',
            constraint=models.UniqueConstraint(fields=('family', 'user'), name='savings_family_membership_uniq'),
        ),
    ]
