# Generated by Django 6.0.4 on 2026-05-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_family_and_scope_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='name',
        ),
    ]
