# Generated by Django 6.0.4 on 2026-05-01 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_rename_distribution_and_simplify_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='distribution',
            name='savings_distribution_scope_family_consistent',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount distributed in this run (signed).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='savings.family'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='distribution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('family__isnull', True), ('scope', 'PERSONAL')), models.Q(('family__isnull', False), ('scope', 'FAMILY')), _connector='OR'), name='savings_distribution_scope_family_consistent'),
        ),
    ]
