"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-l&r26ru+8b%9p%fq(u&i_lip!7=l4)72$js=r4)min=1l==mxu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["api.yukiclaire.xyz", "api.yukiclaire.cl", "localhost"]


def _csrf_trusted_origins() -> list[str]:
    """Build CSRF trusted origins from ALLOWED_HOSTS plus optional env override."""
    out: list[str] = []
    for host in ALLOWED_HOSTS:
        if not host or host == "*":
            continue
        if host in {"localhost", "127.0.0.1", "[::1]"}:
            out.extend((f"http://{host}", f"https://{host}"))
        else:
            out.append(f"https://{host}")
            if DEBUG:
                out.append(f"http://{host}")
    extra = os.getenv("CSRF_TRUSTED_ORIGINS", "").strip()
    if extra:
        out.extend(o.strip() for o in extra.split(",") if o.strip())
    # Deduplicate while preserving order
    return list(dict.fromkeys(out))


CSRF_TRUSTED_ORIGINS = _csrf_trusted_origins()


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "flags",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_q",
    "auth.apps.AuthConfig",
    "pagechecker",
    "groceries",
    "savings",
    "manga",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


def _postgres_from_url(url: str) -> dict:
    """Build Django DATABASES entry from POSTGRES_URL (postgresql:// or postgres://)."""
    parsed = urlparse(url)
    if parsed.scheme not in {"postgresql", "postgres"}:
        msg = f"POSTGRES_URL must use postgresql:// or postgres:// scheme, got {parsed.scheme!r}"
        raise ValueError(msg)
    query = parse_qs(parsed.query)
    options: dict[str, str] = {}
    if "sslmode" in query and query["sslmode"]:
        options["sslmode"] = query["sslmode"][0]
    name = (parsed.path or "").lstrip("/") or ""
    if not name:
        msg = "POSTGRES_URL must include a database name in the path"
        raise ValueError(msg)
    cfg: dict = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(name),
        "USER": unquote(parsed.username) if parsed.username else "",
        "PASSWORD": unquote(parsed.password) if parsed.password else "",
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port) if parsed.port else "",
    }
    if options:
        cfg["OPTIONS"] = options
    return cfg


_sqlite_path = Path(os.getenv("SQLITE_PATH", str(BASE_DIR / "db.sqlite3"))).expanduser()

POSTGRES_URL = os.getenv("POSTGRES_URL", "").strip()

if POSTGRES_URL:
    DATABASES = {
        "default": _postgres_from_url(POSTGRES_URL),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": _sqlite_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Santiago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

_staticfiles_backend = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": _staticfiles_backend,
    },
}


cors_allowed_origins = os.getenv("CORS_ALLOWED_ORIGINS", "").strip()

if cors_allowed_origins:
    CORS_ALLOWED_ORIGINS = [
        origin.strip() for origin in cors_allowed_origins.split(",") if origin.strip()
    ]
elif DEBUG:
    # Development default: allow requests from any local/frontend origin.
    CORS_ALLOW_ALL_ORIGINS = True

# JWT access tokens (login: `/api/v1.Auth.Login`)
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", "").strip() or SECRET_KEY
JWT_ALGORITHM = "HS256"
JWT_SIGNING_KEY = JWT_SECRET_KEY
JWT_ACCESS_TOKEN_LIFETIME_SECONDS = int(
    os.getenv("JWT_ACCESS_TOKEN_LIFETIME_SECONDS", str(7 * 24 * 3600))
)

# django-flags — https://cfpb.github.io/django-flags/
# RUNNING_LOW_SCHEDULED_SYNC: enable groceries daily django-q enqueue for running-low
# sync. Empty here; toggle boolean in Django admin (FlagState) when deployed.
FLAGS: dict[str, list] = {
    "RUNNING_LOW_SCHEDULED_SYNC": [],
}

# django-q2 task queue — ORM broker (uses the default SQLite database)
Q_CLUSTER = {
    "name": "pagechecker",
    "workers": int(os.getenv("Q_WORKERS", "2")),
    "timeout": 240,
    "retry": 300,
    "orm": "default",
    "catch_up": False,
    "ack_failures": True,
    "max_attempts": 3,
    "label": "Task Queue",
}

MANGA_ROOT = os.getenv("MANGA_ROOT", "/manga")

# Google Drive (service account JSON). Upload jobs write under folder named ``MANGA_GOOGLE_DRIVE_ROOT_FOLDER_NAME``.
# Share that folder (Editor) with the service account client_email from the JSON key.
GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE = os.getenv("GOOGLE_DRIVE_SERVICE_ACCOUNT_FILE", "").strip()
GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON", "").strip()
MANGA_GOOGLE_DRIVE_ROOT_FOLDER_NAME = os.getenv("MANGA_GOOGLE_DRIVE_ROOT_FOLDER_NAME", "Manga").strip() or "Manga"

# MangaBaka API (optional overrides for tests or self-hosted mirror)
MANGABAKA_API_BASE_URL = os.getenv("MANGABAKA_API_BASE_URL", "https://api.mangabaka.dev/v1/")
MANGABAKA_HTTP_USER_AGENT = os.getenv("MANGABAKA_HTTP_USER_AGENT", "hs-backend-manga/1.0")
MANGABAKA_INFO_SYNC_BATCH_SIZE = int(os.getenv("MANGABAKA_INFO_SYNC_BATCH_SIZE", "5"))
MANGABAKA_HTTP_DELAY_SECONDS = float(os.getenv("MANGABAKA_HTTP_DELAY_SECONDS", "0.5"))
MANGABAKA_TITLE_MATCH_THRESHOLD = int(os.getenv("MANGABAKA_TITLE_MATCH_THRESHOLD", "90"))
MANGABAKA_SEARCH_LIMIT = int(os.getenv("MANGABAKA_SEARCH_LIMIT", "12"))

# LocMem cache (default backend).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "backend-default",
    }
}
