# Generated by Django 6.0.4 on 2026-04-18 13:04

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='groceries_product_name_lower_uniq'),
        ),
    ]
