# Generated by Django 6.0.4 on 2026-04-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_bought_at',
        ),
    ]
