# Generated by Django 6.0.4 on 2026-04-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_remove_product_last_bought_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='purchases', to='groceries.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
