# Generated by Django 6.0.4 on 2026-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_product_name_case_insensitive_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
