# Generated by Django 6.0.4 on 2026-04-18

from django.db import migrations, models
from django.db.models import F


def backfill_original_name(apps, schema_editor):
    Product = apps.get_model("groceries", "Product")
    Product.objects.filter(original_name="").update(original_name=F("name"))


class Migration(migrations.Migration):

    dependencies = [
        ("groceries", "0004_product_brand_price_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(backfill_original_name, migrations.RunPython.noop),
    ]
