# Generated by Django 6.0.4 on 2026-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groceries", "0005_product_original_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Purchase",
            new_name="Basket",
        ),
        migrations.AddField(
            model_name="basket",
            name="purchased_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basket",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="baskets",
                to="groceries.product",
            ),
        ),
    ]
