# Generated by Django 6.0.4 on 2026-04-18 18:22

import re
from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def _parse_legacy_price(raw: str) -> Decimal:
    """Map old free-text price (e.g. '$3.990', '1000') to Decimal CLP."""
    if not raw or not str(raw).strip():
        return Decimal("0")
    s = str(raw).strip().replace("$", "").replace("CLP", "").strip()
    s = re.sub(r"\s+", "", s)
    if not s:
        return Decimal("0")
    # Prefer digits-only path for Chilean thousand separators (3.990 → 3990)
    digits_only = re.sub(r"[^\d]", "", s)
    if digits_only:
        try:
            return Decimal(digits_only)
        except InvalidOperation:
            pass
    try:
        return Decimal(s.replace(",", "."))
    except InvalidOperation:
        return Decimal("0")


def forwards_copy_price(apps, schema_editor):
    Product = apps.get_model("groceries", "Product")
    for row in Product.objects.all().only("pk", "price_old"):
        row.price = _parse_legacy_price(row.price_old)
        row.save(update_fields=["price"])


def backwards_restore_price(apps, schema_editor):
    Product = apps.get_model("groceries", "Product")
    for row in Product.objects.all().only("pk", "price", "price_old"):
        row.price_old = str(row.price) if row.price is not None else ""
        row.save(update_fields=["price_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("groceries", "0010_product_emoji_remove_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="details",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="price_old",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
            ),
        ),
        migrations.RunPython(forwards_copy_price, backwards_restore_price),
        migrations.RemoveField(
            model_name="product",
            name="price_old",
        ),
    ]
