# Generated by Django 6.0.4 on 2026-04-18

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Sum


def _sync_totals(apps, schema_editor):
    Basket = apps.get_model("groceries", "Basket")
    for basket in Basket.objects.all().iterator():
        agg = basket.products.aggregate(s=Sum("price"))["s"]
        basket.total = agg if agg is not None else Decimal("0")
        basket.save(update_fields=["total"])


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0011_product_price_decimal_remove_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=12,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(_sync_totals, migrations.RunPython.noop),
    ]
