# Generated by Django 6.0.4 on 2026-04-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0011_product_price_decimal_remove_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
