# Generated by Django 6.0.4 on 2026-04-18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0012_basket_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="total",
        ),
    ]
