# Generated by Django 6.0.4 on 2026-04-19 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0013_remove_product_original_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='associated_users',
            field=models.ManyToManyField(blank=True, related_name='associated_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
