# Generated by Django 6.0.4 on 2026-04-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0016_alter_product_user_related_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='groceries_product_name_lower_uniq',
        ),
    ]
