# Generated by Django 6.0.4 on 2026-04-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_products_without_user(apps, schema_editor):
    Product = apps.get_model("groceries", "Product")
    Product.objects.filter(user_id__isnull=True).delete()


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("groceries", "0017_remove_product_groceries_product_name_lower_uniq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_products_without_user, backwards_noop),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
