# Generated by Django 6.0.4 on 2026-04-19

from django.db import migrations, models
from django.db.models import Count


def backfill_purchase_count(apps, schema_editor):
    Basket = apps.get_model("groceries", "Basket")
    Product = apps.get_model("groceries", "Product")
    Through = Basket.products.through
    rows = (
        Through.objects.filter(basket__purchased_at__isnull=False)
        .values("product_id")
        .annotate(n=Count("id"))
    )
    for row in rows:
        Product.objects.filter(pk=row["product_id"]).update(purchase_count=row["n"])


def clear_purchase_count(apps, schema_editor):
    Product = apps.get_model("groceries", "Product")
    Product.objects.all().update(purchase_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ("groceries", "0018_product_user_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="purchase_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_purchase_count, clear_purchase_count),
    ]
