# Generated by Django 6.0.4 on 2026-04-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groceries", "0022_merchant_preference_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="running_low",
            field=models.BooleanField(default=False),
        ),
    ]
