# Generated by Django 6.0.4 on 2026-04-19

from django.db import migrations, models


def copy_m2m_to_through(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO groceries_basketproduct (basket_id, product_id, purchase)
            SELECT basket_id, product_id, %s
            FROM groceries_basket_products
            """,
            [True],
        )


def clear_through(apps, schema_editor):
    BasketProduct = apps.get_model("groceries", "BasketProduct")
    BasketProduct.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("groceries", "0024_daily_running_low_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasketProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase", models.BooleanField(default=True)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        to="groceries.basket",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        to="groceries.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("basket", "product")},
            },
        ),
        migrations.RunPython(copy_m2m_to_through, clear_through),
        migrations.RemoveField(
            model_name="basket",
            name="products",
        ),
        migrations.AddField(
            model_name="basket",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="baskets",
                through="groceries.BasketProduct",
                to="groceries.product",
            ),
        ),
    ]
