# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0033_search_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="recipe_merge_plan",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
