# Generated by Django 5.1

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0034_search_recipe_merge_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="search",
            name="recipe_merge_plan",
        ),
    ]
