# Generated by Django 5.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0036_recipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional quantity or measure (e.g. 2 cups, 1 tbsp).",
                        max_length=255,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_ingredient_lines",
                        to="groceries.product",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="groceries.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ("recipe", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="groceries.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ("recipe", "order", "id"),
            },
        ),
    ]
