# Generated by Django 5.1

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0037_recipeingredient_recipestep"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="product",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="body",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="source_url",
        ),
    ]
