# Generated by Django 6.0.4 on 2026-04-25 03:59

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0042_remove_search_kind_and_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='search',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('assistant_answer', models.TextField()),
                ('recipe_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groceries.recipe')),
            ],
            options={
                'ordering': ('recipe', 'created_at', 'id'),
            },
        ),
    ]
