# Generated by Django 6.0.4 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0043_recipe_message'),
    ]

    operations = [
        migrations.AddField(
            model_name="recipemessage",
            name="gemini_response_raw",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full model response text from Gemini (before structured parse).",
            ),
        ),
    ]
