# Generated by Django 6.0.4 on 2026-04-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0048_product_running_low_snoozed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
